### PR TITLE
This is just too epic

### PR DESCRIPTION
**Pull request by yeah-its-gloria**
- Better code.
- More efficient code.
- Worth it.

### CODE REVIEW

**Comment by Mkwiiripper** [comment]
@apfel good pull request but dont delete the old files so close it then maked again but whithaout deleting a old files thanks

**Comment by yeah-its-gloria** [comment]
*This is a replacement*

**Comment by Puppercino** [comment]
Although C# can be a pretty cool language, it doesn’t invoke the requirement to replace the (easier to use) Batch and Shell scripts.
I’ll merge the files, but not delete the originals. (Just let me get to a computer.)

**Comment by yeah-its-gloria** [comment]
I will restore the old files and put them in another folder.

**Comment by yeah-its-gloria** [comment]
There you go.

**Comment by Puppercino** [comment]
OWO

**Comment by yeah-its-gloria** [comment]
ikr

**Pull request merged**
